import json
import os
from pathlib import Path

# Define the quest directory
quest_dir = Path("content/quests/python-thinking")

# Process each JSON file
for quest_file in sorted(quest_dir.glob("*.json")):
    print(f"Processing: {quest_file.name}")
    
    with open(quest_file, 'r', encoding='utf-8') as f:
        quest = json.load(f)
    
    # Fix hint structure: tier → level, content → text
    if 'hints' in quest:
        for hint in quest['hints']:
            if 'tier' in hint:
                hint['level'] = hint.pop('tier')
            if 'content' in hint:
                hint['text'] = hint.pop('content')
    
    # Fix code fields
    if 'hiddenCode' in quest:
        quest['solutionHidden'] = quest.pop('hiddenCode')
    if 'expectedOutput' in quest:
        del quest['expectedOutput']
    
    # Add missing fields for predict_output
    if quest.get('type') == 'predict_output' and 'starterCode' not in quest:
        quest['starterCode'] = ""
    
    # Add hintUnlockAttempts if missing
    if 'hintUnlockAttempts' not in quest:
        quest['hintUnlockAttempts'] = 2
    
    # Fix difficulty values
    if quest.get('difficulty') == 'medium':
        quest['difficulty'] = 'intermediate'
    if quest.get('difficulty') == 'hard':
        quest['difficulty'] = 'advanced'
    if quest.get('difficulty') == 'easy':
        quest['difficulty'] = 'beginner'
    
    # Add order if missing (extract from filename)
    if 'order' not in quest:
        filename = quest_file.stem
        if filename[:2].isdigit():
            quest['order'] = int(filename[:2])
        else:
            quest['order'] = 1
    
    # Ensure tests array has at least one test
    if not quest.get('tests'):
        quest['tests'] = [{
            "id": f"{quest['id']}-test-1",
            "type": "output",
            "description": "Test placeholder",
            "expectedBehavior": "Generated by schema fixer"
        }]
    
    # Write back
    with open(quest_file, 'w', encoding='utf-8') as f:
        json.dump(quest, f, indent=2, ensure_ascii=False)
    
    print(f"  ✓ Fixed {quest_file.name}")

print("\nAll quests fixed!")
